name: Build Dataflow Flex Template

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Make a choice
        options:
        - main  
        - dev
        - stage

env:
  GCP_REGION: us-central1
  BUCKET_NAME: dataflow-test-ashish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
   #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
 
    - name: Build Dataflow Flex Template
      run: |
        gcloud dataflow flex-template build gs://${{ env.BUCKET_NAME }}/getting_started-py.json \
        --image-gcr-path "${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dataflow-testing/getting-started-python:latest" \
        --sdk-language "PYTHON" \
        --flex-template-base-image "PYTHON3" \
        --metadata-file "metadata.json" \
        --py-path "." \
        --env "FLEX_TEMPLATE_PYTHON_PY_FILE=test.py" \
        --EXPOSE "8080" \
        --env "FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt"
    
    - name: Run Dataflow Flex Template
      run: |
        gcloud dataflow flex-template run "flex-$(date +'%Y%m%d-%H%M%S')" \
        --template-file-gcs-location "gs://${{ env.BUCKET_NAME }}/getting_started-py.json" \
        --region ${{ env.GCP_REGION }} \
        --parameters output="gs://${{ env.BUCKET_NAME }}/output-"
